cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'railwaycat/emacsmacport'
tap 'thoughtbot/formulae'

brew 'ack'
brew 'autojump'
brew 'aws-keychain'
brew 'awscli'
brew 'cask'
brew 'clojurescript'
brew 'curl'
brew 'dnsmasq'
brew 'editorconfig'
brew 'emacs-mac'
brew 'git'
brew 'htop'
brew 'hub'
brew 'icdiff'
brew 'imagemagick'
brew 'mas'
brew 'nginx'
brew 'nvm'
brew 'rbenv'
brew 'rcm'
brew 'reattach-to-user-namespace'
brew 'redis'
brew 'rlwrap'
brew 'siege'
brew 'the_silver_searcher'
brew 'tmux'
brew 'webp'
brew 'zlib'
brew 'zsh'

cask 'adobe-creative-cloud'
cask 'alfred'
cask 'android-studio'
cask 'archiver'
cask 'dropbox'
cask 'google-chrome'
cask 'hipchat'
cask 'iterm2'
cask 'java'
cask 'karabiner-elements'
cask 'numi'
cask 'sequel-pro'
cask 'skype'
cask 'spotify'
cask 'teamviewer'
cask 'telegram-desktop'
cask 'textual'
cask 'tunnelbear'
cask 'virtualbox'
cask 'vlc'

mas 'Xcode', id: 497799835 
