# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @catppuccin_flavor 'mocha'

# set history length
set-option -g history-limit 10000

# vi mode for tmux
setw -g mode-keys vi

# Set prefix command to Ctrl-b
set -g prefix C-b

# Binding to allow sending the prefix combination
bind C-a send-prefix

# Reduce tmux delay for more responsiveness
set -sg escape-time 1

# Window and pane index count starts in 1 rather tan 0
set -g base-index 1
setw -g pane-base-index 1

# Dividers
bind | split-window -h
bind - split-window -v

setw -g mouse on
bind-key -T root WheelUpPane if-shell -F -t = "#{alternate_on}" "send-keys -M" "select-pane -t =; copy-mode -e; send-keys -M"
bind-key -T root WheelDownPane if-shell -F -t = "#{alternate_on}" "send-keys -M" "select-pane -t =; send-keys -M"

# theme
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"

# Ensure that everything on the right side of the status line
# is included.
set -g status-right-length 100

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'