;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        crux-move-beginning-of-line
        haml-electric-backspace
        helm-M-x
        helm-projectile-ag
        mac-mwheel-scroll
        markdown-exdent-or-delete
        sp-backward-delete-char
        sp-backward-kill-word
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        coffee-dedent-line-backspace
        end-of-buffer
        eval-buffer
        eval-defun
        helm-mini
        helm-recentf
        helm-show-kill-ring
        magit-status
        mouse-set-region
        next-buffer
        previous-buffer
        ))
