;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        crux-move-beginning-of-line
        haml-electric-backspace
        helm-M-x
        mac-mwheel-scroll
        sp-backward-delete-char
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        coffee-dedent-line-backspace
        end-of-buffer
        eval-buffer
        helm-show-kill-ring
        magit-status
        previous-buffer
        ))
