#!/usr/bin/env bash

#################
# system settings

# Reveal IP address, hostname, OS version, etc. when clicking the clock
# in the login window
sudo defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo HostName

## Keyboard
# Set fast keyboard repeat rate
defaults write NSGlobalDomain KeyRepeat -float 1
# Set fn keys to FNn
defaults write -g com.apple.keyboard.fnState -bool TRUE

## File System
# Show the ~/Library folder
chflags nohidden ~/Library
# Show the /Volumes folder
sudo chflags nohidden /Volumes

## Dock
# Automatically hide and show the Dock
defaults write com.apple.dock autohide -bool TRUE
# Show only open application on Dock
defaults write com.apple.dock static-only -bool TRUE
# Change minimize/maximize window effect
defaults write com.apple.dock mineffect -string "scale"
# restart dock
killall Dock

# Sleep time
sudo systemsetup -setcomputersleep 10

## Mouse
# normal mouse scroll direction
defaults write -g com.apple.swipescrolldirection -bool NO
# right click
defaults write com.apple.driver.AppleBluetoothMultitouch.mouse MouseButtonMode TwoButton

#########
# ohmyzsh
git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh

###########
# spacemacs
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.e

###############
# Dotfiles init
brew tap thoughtbot/formulae
brew install rcm
env RCRC=/Users/am/.dotfiles/rcrc rcup

echo "Done. Now the default shell will be changed to zsh."

chsh -s /bin/zsh
